on:
  workflow_call:
    inputs:
      rust-version:
        type: string
        required: false
        default: nightly

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        ref: ${{ GITHUB_REF##*/ }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust-version }}
          override: true
          components: rustfmt, clippy
      # - name: Set up cargo cache
      #   uses: actions/cache@v3
      #   continue-on-error: false
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo-cache3-${{ hashFiles('**/Cargo.toml') }}
      #     restore-keys: ${{ runner.os }}-cargo-cache3-

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Install cargo-deny
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-deny
      - name: Install cargo-outdated
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-outdated
      - name: Install cargo-udeps
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-udeps
      - name: Install cargo-audit
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-audit
      - name: Install cargo-pants
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-pants
      - name: Check
        run: |
          #cargo deny check
          cargo outdated
          #cargo udeps
          #cargo audit
          cargo pants
