on:
  workflow_call:
    inputs:
      rust-version:
        type: string
        required: false
        default: nightly
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cargo test w/ all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Cargo test w/ no default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
      # Specific feature checks should go into the user's
      # crate, not here.

